name: Backend

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Installing Dependencies
        run: dotnet restore document-editor.sln
        working-directory: Backend

      - name: Format
        run: dotnet format document-editor.sln --verify-no-changes
        working-directory: Backend
        
      - name: Test
        run: dotnet test document-editor.sln
        working-directory: Backend