name: Frontend

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Installing Dependencies
        run: npm ci
        working-directory: Frontend

      - name: Linting
        run: npx ng lint
        working-directory: Frontend

      - name: Building
        run: npx ng build
        working-directory: Frontend