name: "documentEditor"

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Setup Angular CLI
        run: npm install -g @angular/cli

      - name: Installing Dependencies
        run: npm ci
        working-directory: Frontend

      - name: Linting
        run: ng lint
        working-directory: Frontend
        
